dbases:
  - name: EP1
    driver: mssql
    host: sapprd.arthomson.com
    port: 1433
    database: EP1
    schema:
      - ep1
    username: sadmin
    password: G0tAdmin
    poolsize: 90
  - name: EQ1
    driver: mssql
    host: sapdev.arthomson.com
    port: 1433
    database: EQ1
    schema:
      - eq1
    username: sadmin
    password: G0tAdmin
    poolsize: 90
  - name: ED1
    driver: mssql
    host: sapdev.arthomson.com
    port: 1433
    database: ED1
    schema:
      - ed1
    username: sadmin
    password: G0tAdmin
    poolsize: 90
  - name: reports
    driver: mssql
    host: reports.arthomson.com
    port: 1433
    database: reports
    schema:
      - ct
      - dbo
      - ep1
      - odoo
      - sapdata
    username: sapdatarw
    password: Gasket2008
    poolsize: 90
  - name: artg
    driver: postgres
    host: db.arthomson.com
    port: 5432
    database: artg
    schema:
      - aims
      - beslogs
      - ct
      - customreports
      - ed1
      - ep1
      - eq1
      - odoo
      - reportsubs
      - sap
      - sapdata
      - sapdb
    username: sadmin
    password: aWk7XbNujFiDsi
    poolsize: 90
  - name: artg2
    driver: postgres
    host: odootest2.arthomson.com
    port: 5432
    database: artg
    schema:
      - aims
      - beslogs
      - ct
      - customreports
      - ed1
      - ep1
      - eq1
      - odoo
      - reportsubs
      - sapdata
    username: sadmin
    password: aWk7XbNujFiDsi
    poolsize: 90
  - name: sapdb
    driver: postgres
    host: db.arthomson.com
    port: 5432
    database: sapdb
    schema:
      - aims
      - ct
      - odoo
      - reportsubs
      - sapdata
    username: sapdatarw
    password: Gasket2008
    poolsize: 90
  - name: KCCSafety
    driver: mssql
    host: reports.arthomson.com
    port:
    database: KCCSafety
    schema: [dbo]
    username: sapdatarw
    password: Gasket2008
    poolsize: 90
  - name: delpro
    driver: postgres
    host: db.arthomson.com
    port:
    database: delpro
    schema:
      - antdat
      - antsys
      - bdsmgmt
      - delcom
      - delstm
      - deltst
      - elim
      - elimsy
      - esconatutorial
      - maconfig
      - norcom
      - norsys
      - quotewerks
      - tekcom
      - tekstm
      - twmdat
      - twmsys
      - valcom
      - valstm
    username: sadmin
    password: aWk7XbNujFiDsi
    poolsize: 90

  - name: ANTDAT
    driver: mssql
    host: 192.168.20.213
    port:
    database: ANTDAT
    schema:
      - dbo
    username: sadmin
    password: aWk7XbNujFiDsi
    poolsize: 90

  - name: ANTSYS
    driver: mssql
    host: 192.168.20.213
    port:
    database: ANTSYS
    schema:
      - dbo
    username: sadmin
    password: aWk7XbNujFiDsi
    poolsize: 90

  - name: BDSMgmt
    driver: mssql
    host: 192.168.20.213
    port:
    database: BDSMgmt
    schema:
      - dbo
    username: sadmin
    password: aWk7XbNujFiDsi
    poolsize: 90

  - name: DELCOM
    driver: mssql
    host: 192.168.20.213
    port:
    database: DELCOM
    schema:
      - dbo
    username: sadmin
    password: aWk7XbNujFiDsi
    poolsize: 90

  - name: DELSTM
    driver: mssql
    host: 192.168.20.213
    port:
    database: DELSTM
    schema:
      - dbo
    username: sadmin
    password: aWk7XbNujFiDsi
    poolsize: 90

  - name: DELTST
    driver: mssql
    host: 192.168.20.213
    port:
    database: DELTST
    schema:
      - dbo
    username: sadmin
    password: aWk7XbNujFiDsi
    poolsize: 90

  - name: ELIM
    driver: mssql
    host: 192.168.20.213
    port:
    database: ELIM
    schema:
      - dbo
    username: sadmin
    password: aWk7XbNujFiDsi
    poolsize: 90

  - name: ELIMSY
    driver: mssql
    host: 192.168.20.213
    port:
    database: ELIMSY
    schema:
      - dbo
    username: sadmin
    password: aWk7XbNujFiDsi
    poolsize: 90

  - name: EsconaTutorial
    driver: mssql
    host: 192.168.20.213
    port:
    database: EsconaTutorial
    schema:
      - dbo
    username: sadmin
    password: aWk7XbNujFiDsi
    poolsize: 90

  - name: MaConfig
    driver: mssql
    host: 192.168.20.213
    port:
    database: MaConfig
    schema: [dbo]
    username: sadmin
    password: aWk7XbNujFiDsi
    poolsize: 90

  - name: NORCOM
    driver: mssql
    host: 192.168.20.213
    port:
    database: NORCOM
    schema: [dbo]
    username: sadmin
    password: aWk7XbNujFiDsi
    poolsize: 90

  - name: NORSYS
    driver: mssql
    host: 192.168.20.213
    port:
    database: NORSYS
    schema:
      - dbo
    username: sadmin
    password: aWk7XbNujFiDsi
    poolsize: 90

  - name: QuoteWerks
    driver: mssql
    host: 192.168.20.213
    port:
    database: QuoteWerks
    schema:
      - dbo
    username: sadmin
    password: aWk7XbNujFiDsi
    poolsize: 90

  - name: TEKCOM
    driver: mssql
    host: 192.168.20.213
    port:
    database: TEKCOM
    schema:
      - dbo
    username: sadmin
    password: aWk7XbNujFiDsi
    poolsize: 90

  - name: TEKSTM
    driver: mssql
    host: 192.168.20.213
    port:
    database: TEKSTM
    schema:
      - dbo
    username: sadmin
    password: aWk7XbNujFiDsi
    poolsize: 90

  - name: TWMDAT
    driver: mssql
    host: 192.168.20.213
    port:
    database: TWMDAT
    schema:
      - dbo
    username: sadmin
    password: aWk7XbNujFiDsi
    poolsize: 90

  - name: TWMSYS
    driver: mssql
    host: 192.168.20.213
    port:
    database: TWMSYS
    schema:
      - dbo
    username: sadmin
    password: aWk7XbNujFiDsi
    poolsize: 90

  - name: VALCOM
    driver: mssql
    host: 192.168.20.213
    port:
    database: VALCOM
    schema:
      - dbo
    username: sadmin
    password: aWk7XbNujFiDsi
    poolsize: 90

  - name: VALSTM
    driver: mssql
    host: 192.168.20.213
    port:
    database: VALSTM
    schema:
      - dbo
    username: sadmin
    password: aWk7XbNujFiDsi
    poolsize: 90
